-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
    -   id: flake8
        exclude: (migrations|ui)

-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: v2.8.0
    hooks:
    -   id: jshint
        files: ui/source/js/.+\.js
