-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
    -   id: flake8
        exclude: (migrations|ui)

-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: v2.4.0
    hooks:
    -   id: eslint
        files: ui/source/js/.+\.js
