sudo: required

language: python
cache:
  directories:
    - /home/travis/.cache/pip
    - /home/travis/.cypress/Cypress
    - /home/travis/refinery-platform/deployment/puppet/modules

install:
  - sh deployment/bootstrap.sh
  - puppet apply --environment_path "deployment/puppet" --environment "travis"
  - workon refinery-platform

env:
  global:
    # These env vars are available to every build
    # CYPRESS_RECORD_KEY:
    - secure: oGdTYh3rnPdG7qVGYq3TgVESypir1btO2kmafumtKR6o+FYmMtb09pe+HtiT6Qfv4pDwnYZ2RTYqsTY4h6POigU5j7qQPSsZ5WkhHt9ybFyt/vfo2B95GaAIFt+8LVjTX5TItyw0/PPUCCUluQ1n8k/NCtSfMb0kIT/CuLrg7N8=

before_script:
  - cd refinery

script:
  - set -e # Any error will cause travis to exit early and report a failure.

  # TODO: Not the same behavior as pre-commit hook.
  # https://github.com/refinery-platform/refinery-platform/issues/1851
  - flake8 ..

  - echo 'travis_fold:start:grunt'
  - pushd ui && grunt test && popd
  - echo 'travis_fold:end:grunt'

  - echo 'travis_fold:start:django-tests'
  - coverage run manage.py test
  - echo 'travis_fold:end:django-tests'

  - echo 'travis_fold:start:cypress'
  - pushd ui && node_modules/.bin/cypress run --record && popd
  - echo 'travis_fold:end:cypress'

  - set +e # Currently, codecov does not always exit with 0, but that should not cause travis to fail.

after_success:
  - echo 'travis_fold:start:codecov'
  - codecov
  - npm run codecov
  - echo 'travis_fold:end:codecov'
notifications:
  slack:
    secure: nDs9Oj08nRizuD0edl6WcrSgaTPMyITQjZc4qPZpt+yOxUehWbrAmVhqYypfyvdj4qSi1E72rPTXftuBB1E1IZBgX4CCkrCkWGLgIxHaaValTd64oOX66eC3BbSehQxuJB7w1DWw54xBUkTy6+ufjAqiwhLpoEUeE296urAWYHU=
