language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
env:
  - DJANGO_SETTINGS_MODULE=settings.dev
script:
  - cd refinery
  - python manage.py syncdb --migrate
  - python manage.py file_store test
