language: python
python:
  - 2.7
services:
  - postgresql
  - neo4j
  - memcached
install:
  - pip install -r requirements.txt
env:
  - DJANGO_SETTINGS_MODULE=config.settings.dev
before_script:
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=5.3.1 bash
  - createuser --createdb --no-superuser --no-createrole vagrant
  - createdb -O vagrant refinery
  - cd refinery
  - cp config/config.json.sample config/config.json
  - python manage.py syncdb --migrate --noinput
  - npm install --quiet -g grunt-cli karma bower
  - cd ui && npm install && bower install && cd ../
script:
  - pep8 --exclude=migrations,ui ..
  - coverage run manage.py test
  - cd ui && grunt && cd ../
after_success:
  - codecov
  - npm run codecov
notifications:
  slack:
    secure: nDs9Oj08nRizuD0edl6WcrSgaTPMyITQjZc4qPZpt+yOxUehWbrAmVhqYypfyvdj4qSi1E72rPTXftuBB1E1IZBgX4CCkrCkWGLgIxHaaValTd64oOX66eC3BbSehQxuJB7w1DWw54xBUkTy6+ufjAqiwhLpoEUeE296urAWYHU=
